# Generated by Django 6.0.2 on 2026-03-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('logistics', '0007_alter_request_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='logistics.request'),
            preserve_default=False,
        ),
    ]
