# Generated by Django 6.0.2 on 2026-03-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
