# Generated by Django 6.0.2 on 2026-03-04 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
        ('logistics', '0011_request_volunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='military',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.request'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
