# Generated by Django 6.0.2 on 2026-02-22 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва запиту')),
                ('description', models.TextField(verbose_name='Опис (що саме потрібно)')),
                ('location', models.CharField(max_length=150, verbose_name='Локація / Напрямок')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('completed', 'Виконано'), ('rejected', 'Відхилено')], default='new', max_length=20, verbose_name='Статус')),
                ('urgency', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=20, verbose_name='Терміновість')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='Причина відхилення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
