# Generated by Django 6.0.2 on 2026-02-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару (напр. Mavic 3T)')),
                ('category', models.CharField(choices=[('medicine', 'Медицина'), ('drones', 'Дрони та електроніка'), ('ammunition', 'Амуніція'), ('vehicles', 'Транспорт'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Категорія')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість на складі')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
        ),
    ]
