# Generated by Django 6.0.2 on 2026-02-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_warehouseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('awaiting_purchase', 'Очікує закупівлі'), ('completed', 'Виконано'), ('rejected', 'Відхилено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
