# Generated by Django 6.0.2 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/', verbose_name='Скан від військової частини'),
        ),
    ]
