# Generated by Django 6.0.2 on 2026-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_request_attachment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/', verbose_name='Скан від військової частини'),
        ),
    ]
