# Generated by Django 6.0.2 on 2026-03-01 17:16

import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_request_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=logistics.models.attachment_path, verbose_name='Скан від військової частини'),
        ),
    ]
