# Generated by Django 6.0.2 on 2026-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_request_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
    ]
