# Generated by Django 6.0.2 on 2026-03-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_request_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(verbose_name='Зміна кількості (+/-)')),
                ('description', models.CharField(max_length=255, verbose_name='Опис транзакції')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='logistics.warehouseitem', verbose_name='Товар')),
                ('logistics_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.request', verbose_name="Пов'язана заявка")),
            ],
        ),
    ]
