# Generated by Django 6.0.2 on 2026-03-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_stocktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('completed', 'Виконано'), ('rejected', 'Відхилено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='Старий статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новий статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив')),
                ('logistics_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='logistics.request', verbose_name='Заявка')),
            ],
        ),
    ]
