# Generated by Django 6.0.2 on 2026-02-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Оголошення'},
        ),
    ]
