# Generated by Django 6.0.2 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='price',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
