# Generated by Django 6.0.2 on 2026-02-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medicine', 'Медицина'), ('drones', 'Дрони та електроніка'), ('ammunition', 'Амуніція'), ('vehicles', 'Транспорт'), ('other', 'Інше')], default='other', max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UAH', max_length=10)),
                ('link', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='suppliers.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='suppliers_s_categor_fe6b62_idx'), models.Index(fields=['item_name'], name='suppliers_s_item_na_36f1fd_idx'), models.Index(fields=['is_available'], name='suppliers_s_is_avai_3a4c84_idx')],
            },
        ),
    ]
