# Generated by Django 6.0.2 on 2026-03-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplieroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieroffer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
